### PR TITLE
Adding Tech on toast group , hardening and testing name matching

### PR DESCRIPTION
**Pull request by sdh100shaun**
Have added a normaliseName function to meetupAdapter and a couple of unit tests - expected behaviour where group has multiple events is for evet to show up under both - is this desirable?  Maybe need to check if the url is reused then the check should be exclude events in main group where there is a matcher?

### CODE REVIEW

**Comment by sdh100shaun** [comment]
@jhigman maybe you want to comment on this ...  should groups with more than one event get there event times also listed against main event?

**Comment by jhigman** [comment]
Seems like it would be better for event times to only be listed with the specific event title - so Tech Nottingham would only show the dates for Tech Nottingham meetups, not for Tech on Toast (which would be shown only for the 'Tech on Toast' title).. if I've understood correctly what the question is..!

**Comment by sdh100shaun** [comment]
@jhigman yes agree that's the best option will take a bit more work - just to pre-parse config and check etc

**Comment by sdh100shaun** [comment]
Done a temporary fix on the problem with adding match to both events - will speak with Andrew Seward

**Pull request closed without merging**
