### PR TITLE
Adding Cyber Security Nottingham

### PR DESCRIPTION
**Pull request by crossowl**

### CODE REVIEW

**Comment by crossowl** [comment]
Thanks :)
https://github.com/nottinghamdigital/nottinghamdigital.github.io/pull/101

**Comment by sdh100shaun** [comment]
will get this merged asap,

**Comment by crossowl** [comment]
no rush, looks like a dependency is 404ing

**Comment by crossowl** [comment]
Yup, that's looking better

**Comment by crossowl** [comment]
Can somebody please merge?

**Pull request merged**
